<div class="left categorylist">
    <?= $this->layout()->categoryMain; ?>
    <? if (0 < count($this->subCategories)): ?>
    <div class="sub-nav">
        <h3> In thisa <span>categoryaa:</span></h3>
            <ul>
                <? foreach($this->Subcategories as $category): ?>
                <li>
                    <a href="<?=$this->url(array('categoryIdent' => $category->ident), 'catalog_category', true); ?>">
                    <?=$category->name; ?>
                    </a>
                </li>
                <? endforeach; ?>
            </ul>
    </div>
    <? endif; ?>
    <div>
        <h3>In your <span>cart:</span></h3>
        <?= $this->Cart()->getSummary(); ?>
    </div>
</div>